export const GUARDAR_CONSULTA = 'GUARDAR_CONSULTA';
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS';
export const CARGAR_CATEGORIAS = 'CARGAR_CATEGORIAS';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const MANEJAR_ERROR = 'MANEJAR_ERROR';